version: "3.3"

services:
  mysqld:
    container_name: mysqld
    restart: always
    image: mariadb:10.2.36
    build:
      context: ./
      dockerfile: DockerDB
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_spanish_ci"
      - "--wait_timeout=2800"
      - "--connect_timeout=2800"
      - "--interactive_timeout=2800"
    environment:
      - "TZ=America/Bogota"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=no"
      - "MYSQL_DATABASE=cloud"
      - "MYSQL_USER=cloud"
      - "MYSQL_PASSWORD=cloud123"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./prj/datamodel:/datamodel:rw
    expose:
      - "3306"
    networks:
      cloud:
        ipv4_address: 172.16.200.2

  cloud:
    image: "node:15.14.0"
    user: root
    container_name: cloud
    restart: always
    working_dir: /home/node/app
    build:
      context: ./
      dockerfile: DockerNode
    environment:
      - "TZ=America/Bogota"
      - "NODE_ENV=production"
    volumes:
      - ./prj:/home/node/app:rw
    expose:
      - "8080"
    #ports:
    #  - "80:80"
    depends_on:
      - mysqld
    command: "pm2-runtime app/index.js --watch"
    networks:
      cloud:
        ipv4_address: 172.16.200.3

networks:
  cloud:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/27
